### ISSUE TITLE
Any chance to get maraschino working with Sickrage api?

### ISSUE THREAD

**Issue by slugshell** [mrkipling/maraschino#363]
Hello there, first of all, i love maraschino, lovely interface, you did a great job! 

Here my problem, 
lately I was forced to skip sickbeard and change to a fork called sickrage, only because I need a working databse like tvrage, since thetvdb sadly seems to have difficulties accomplishing this, for example (season order - american dad). 

Problem i have now, sickrage seems to use a different api, please have a look here https://github.com/echel0n/SickRage/blob/master/sickbeard/webapi.py

If i try to use the original sickbeard webapi.py with sickrage i get: 
2014-05-25 14:41:53 CP Server Thread-4 :: DB error: no such column: tv_shows.tvdb_id
2014-05-25 14:41:53 CP Server Thread-4 :: API :: no such column: tv_shows.tvdb_id

Is there any chance for a quick fix? 

Thank you very much, 

greetings, 

slugshell

**Comment by dgwingert** [comment]
Hi all,

I'm new to development, so I hope I'm not stepping on anybody's toes. I took the work done by @Roostayfish and worked it into the version of maraschino with xbmc/kodi support. Can somebody let me know if it works for them? It is currently working for me, but I'm new to github and coding as well.

Here is my repo. Make sure to try the sickrage fork.
https://github.com/dgwingert/maraschino/tree/sickrage

Thanks,
dgwingert

**Comment by Hellowlol** [comment]
I dont think your stepping on any toes maraschino development has been halted for quite some time. You should change the seachtvdb api command, as it only search tvdb. I think there is one called search indexers or something.

**Comment by mboeru** [comment]
Hi,

I can test tomorrow, I will report back here if I find anything. Many thanks for picking this up.

**Comment by Hellowlol** [comment]
@dgwingert See https://github.com/Hellowlol/HTPC-Manager/blob/master2/modules/sickrage.py#L210 for a example to search on tvdb and tvrage for a show at the same time.

**Comment by neoTUGA** [comment]
@dgwingert not working for me :(
KODI is fine, but not connecting to sickrage... :(

**Comment by mboeru** [comment]
Just tested and the sickrage widget does not seem to show anything. And there is nothing about it in the log either.

**Comment by dgwingert** [comment]
Ok, I checked my work more carefully this time. I pushed the new changes to the repo. (https://github.com/dgwingert/maraschino). I downloaded it to another computer and managed to run and connect to sickrage. Let me know if your experience is different of course. @Hellowlol , I'll look into the searchtvdbapi, although time is not something I have a surplus of. Thanks for the help.

**Comment by ebright** [comment]
Hey guys.  I am also working on adding to maraschino, but I am working on the trakt 2.0 api changes.  in the meantime tho, check out this comment https://github.com/ebright/maraschino/commit/781947970ebd843f253fc2fcd79bae6ce1b632a9 to add plot details to the sickrage module

**Comment by mboeru** [comment]
@dgwingert Works well on for me :)
I still have the trakt issue that @ebright fixed in #383

**Comment by dgwingert** [comment]
I suppose the best thing would be for me to merge my branch with somebody who is actively developing, since my contribution was kind-of a one-off. How should I go about making that happen?

**Comment by hadees** [comment]
@dgwingert you need to [make a pull requst](https://help.github.com/articles/using-pull-requests/)
